meal-plan-generator/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using meal_plan_generator.Context;
using meal_plan_generator.Models.MealPlan;
using meal_plan_generator.Context.UnitofWork;
using Microsoft.CodeAnalysis.VisualBasic.Syntax;
using meal_plan_generator.Services;

namespace meal_plan_generator.Controllers
{
    public class FormsController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly ILogger<FormsController> _logger;
        private readonly IService<MealPlan> _service;

        public FormsController(IUnitOfWork uow, ILogger<FormsController> logger, [FromServices] IService<MealPlan> service)
        {
            _uow = uow;
            _logger = logger;
            _service = service;
        }

        // GET: Forms
        public async Task<IActionResult> Index()
        {
            return View(await _uow.FormsRepo.GetAllAsync());
        }

        // GET: Forms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _uow.FormsRepo == null)
            {
                return NotFound();
            }

            var form = await _uow.FormsRepo.GetByIdAsync((int)id);
            if (form == null)
            {
                return NotFound();
            }

            return View(form);
        }

        // GET: Forms/Create
        public IActionResult Create()
        {
            var form = new Form();
            _logger.LogInformation($"Create action called with new form Id: {form.Id}");
            foreach (var n in form.Nutrients)
            {
                _logger.LogInformation($"Nutrient {n.Id}, {n.Name}, {n.Quantity} {n.Unit} " +
                    $"\nSettings {n.Settings.Id}, {n.Settings.LowerBound}, {n.Settings.IdealAmount} {n.Settings.UpperBound} " +
                    $"\nIntercept: {n.Settings.Intercept}, Weight: {n.Settings.Weight}");
            }
            return View(form);
        }

        // POST: Forms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind] Form form)
        {
            _logger.LogInformation($"Form received by Create action: {form}");
            if (ModelState.IsValid)
            {
                _logger.LogInformation("Form data: {@FormData}", form);

                //await _uow.FormsRepo.InsertRecordAsync(form);
                var newMealPlan = await _service.GetNewMealPlanForFormAsync(form);
                _logger.LogInformation(newMealPlan.ToString());
                await _uow.FormsRepo.SaveChangesAsync();
                return Json(form);
            }
            return View();
        }

        // GET: Forms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _uow.FormsRepo == null)
            {
                return NotFound();
            }

            var form = await _uow.FormsRepo.GetByIdAsync((int)id);
            if (form == null)
            {
                return NotFound();
            }
            return View(form);
        }

        // POST: Forms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id")] Form form)
        {
            if (id != form.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _uow.FormsRepo.Update(form);
                    await _uow.FormsRepo.SaveChangesAsync();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FormExists(form.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(form);
        }

        // GET: Forms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _uow.FormsRepo == null)
            {
                return NotFound();
            }

            var form = await _uow.FormsRepo.GetByIdAsync((int)id);
            if (form == null)
            {
                return NotFound();
            }

            return View(form);
        }

        // POST: Forms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_uow.FormsRepo == null)
            {
                return Problem("Entity set 'AppDbContext.Forms'  is null.");
            }
            var form = await _uow.FormsRepo.GetByIdAsync(id);
            if (form != null)
            {
                await _uow.FormsRepo.DeleteAsync(id);
            }

            await _uow.FormsRepo.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FormExists(int id)
        {
            return _uow.FormsRepo.GetByIdAsync(id) != null;
        }
    }
}

meal-plan-generator/Views/Forms/Create.cshtml
@model meal_plan_generator.Models.MealPlan.Form

@{
    ViewData["Title"] = "Create";
}
<h1>Create</h1>
<h4>Nutrient Settings</h4>
<hr />
@using (Html.BeginForm("Create", "Forms", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <h3 class="text-center">Nutrient Data</h3>

        @for (int i = 0; i < Model.Nutrients.Count; i++)
        {
            <h4>@Model.Nutrients[i].Name Range Settings</h4>
            @Html.HiddenFor(model => Model.Nutrients[i].Name)
            @Html.HiddenFor(model => Model.Nutrients[i].Unit)
            @Html.HiddenFor(model => Model.Nutrients[i].Quantity)
            <div class="container text-center">
                <div class="row row-cols-2 align-items-start input-group">
                    <div class="col mb-2">
                        <div class="form-floating mb-2">
                            @Html.EditorFor(model => Model.Nutrients[i].Settings.Weight,  new { htmlAttributes = new { @class = "form-control", min = "1", step = "1", type = "number", placeholder = $"Enter the importance", name = "Weight" } })
                            @Html.LabelFor(model => Model.Nutrients[i].Settings.Weight, new { htmlAttributes = new { @class = "form-label" } })
                        </div>
                    </div>
                    <div class="col mb-2">
                        <div class="form-floating mb-2">
                            @Html.EditorFor(model => Model.Nutrients[i].Settings.Intercept,  new { htmlAttributes = new { @class = "form-control", min = "1", step = "1", type = "number", placeholder = $"Enter the line slope", name = "Intercept" } })
                            @Html.LabelFor(model => Model.Nutrients[i].Settings.Intercept, new { htmlAttributes = new { @class = "form-label" } })
                        </div>
                    </div>
                </div>
                <div class="row row-cols-3 align-items-start input-group">
                    <div class="col mb-3">
                        <div class="form-floating mb-3">
                            @Html.EditorFor(model => Model.Nutrients[i].Settings.LowerBound, new { htmlAttributes = new { @class = "form-control", min = "0", step = "any", type = "number", placeholder = $"Enter the {Model.Nutrients[i].Unit}", name = "LowerBound" } })
                            @Html.LabelFor(model => Model.Nutrients[i].Settings.LowerBound, new { htmlAttributes = new { @class = "form-label" } })
                        </div>
                    </div>
                    <div class="col mb-3">
                        <div class="form-floating mb-3">
                            @Html.EditorFor(model => Model.Nutrients[i].Settings.IdealAmount, new { htmlAttributes = new { @class = "form-control", min = "0", step = "any", type = "number", placeholder = $"Enter the {Model.Nutrients[i].Unit}", name = "IdealAmount" } })
                            @Html.LabelFor(model => Model.Nutrients[i].Settings.IdealAmount, new { htmlAttributes = new { @class = "form-label" } })
                        </div>
                    </div>
                    <div class="col mb-3">
                        <div class="form-floating mb-3">
                            @Html.EditorFor(model => Model.Nutrients[i].Settings.UpperBound, new { htmlAttributes = new { @class = "form-control", min = "0", step = "any", type = "number", placeholder = $"Enter the {Model.Nutrients[i].Unit}", name = "UpperBound" } })
                            @Html.LabelFor(model => Model.Nutrients[i].Settings.UpperBound, new { htmlAttributes = new { @class = "form-label" } })
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

meal-plan-generator/Views/Forms/Delete.cshtml
@model meal_plan_generator.Models.MealPlan.Form

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Form</h4>
    <hr />
    <dl class="row">
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

meal-plan-generator/Views/Forms/Details.cshtml
@model meal_plan_generator.Models.MealPlan.Form

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Form No. @Model.Id</h4>
    <hr />
    <p>@Model.ToString()</p>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

meal-plan-generator/Views/Forms/Edit.cshtml
@model meal_plan_generator.Models.MealPlan.Form

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Form</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

meal-plan-generator/Views/Forms/Index.cshtml
@model IEnumerable<meal_plan_generator.Models.MealPlan.Form>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Form ID</th>
            <th>Nutrient Data</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <span>Form No. @item.Id</span>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
                <td>
                    @foreach (var nutrient in item.Nutrients)
                    {
                        <span>@nutrient.Name: @nutrient.Unit</span>

                        <br />
                    }
                </td>
            </tr>
        }
    </tbody>
</table>